from pathlib import Path
import re
p=Path('/mnt/data/aict_final/assets/app.js')
s=p.read_text()
# config endpoint in state
s=s.replace("aiEndpoint:localStorage.getItem('aict_ai_endpoint')||''", "aiEndpoint:localStorage.getItem('aict_ai_endpoint')||window.AICT_CONFIG?.AI_ENDPOINT||''")
# mobile navigation
s=s.replace("function mobileNav(){return `<div class=\"mobile-nav\">${[['home','🏠'],['library','📚'],['challenge','🎮'],['competition','🏆'],['progress','📈']].map(x=>`<button class=\"${state.page===x[0]?'active':''}\" data-nav=\"${x[0]}\">${x[1]}<br>${x[0]}</button>`).join('')}</div>`}", "function mobileNav(){return `<div class=\"mobile-nav\">${[['home','🏠'],['library','📚'],['cycle','🧠'],['challenge','🎮'],['progress','📈']].map(x=>`<button class=\"${state.page===x[0]?'active':''}\" data-nav=\"${x[0]}\">${x[1]}<br>${x[0]}</button>`).join('')}</div>`}")
# replace cycle block through before gameSetup
start=s.index('function cycle(){')
end=s.index('function gameSetup(kind){')
new=r'''function cycle(){
 if(!state.scenario) pickScenario();
 const s=state.scenario.s;
 return shell(`<div class="game-shell cycle-page">
   <div class="section-title"><div><h2>🧠 AI-CT 6C Critical Thinking Cycle</h2><p>Use AI as a response to examine — not as a final authority.</p></div><span class="pill">6 stages</span></div>
   <div class="sixc">${STAGES.map((x,i)=>`<span class="sixc-step ${i<state.scenario.step?'done':''} ${i===state.scenario.step?'active':''}"><b>${i+1}</b>${x[0]}</span>`).join('')}</div>
   <div class="scenario-hero"><span class="eyebrow">Real classroom context</span><div class="scenario-title-row"><h1>${esc(s[0])}</h1><button class="ghost-btn" data-action="newScenario">🔀 New</button></div><p class="scenario-text">${esc(s[1])}</p></div>
   <div id="sc-q"></div>
 </div>`);
}
function pickScenario(){const i=Math.floor(Math.random()*SCENARIOS.length);state.scenario={i,s:SCENARIOS[i],step:0,responses:{},ai:null,startedAt:new Date().toISOString(),completed:false}}
function startScenario(){pickScenario();render();setTimeout(renderScenario,0);sound('start')}
function scenarioStage(){return STAGES[state.scenario.step]?.[0]||'Context'}
function aiEndpoint(){return state.aiEndpoint||window.AICT_CONFIG?.AI_ENDPOINT||''}
async function requestAI(stage,studentResponse='',task=''){
 const endpoint=aiEndpoint();
 if(!endpoint) throw new Error('AI endpoint is not configured');
 const s=state.scenario.s;
 const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'6c',stage,scenario:s[1],task,studentResponse})});
 if(!r.ok) throw new Error('AI service unavailable');
 const data=await r.json();
 if(!data?.response) throw new Error('Invalid AI response');
 return data;
}
function renderScenario(){
 const root=document.getElementById('sc-q'), st=state.scenario;if(!root||!st)return;
 const s=st.s, stage=st.step;
 let html='';
 if(stage===0){html=`<div class="question-card"><div class="q-meta"><span class="pill">1. Context</span></div><h2 class="q-title">Understand the situation</h2><p>Before asking AI, identify the key classroom problem.</p><div class="answer-summary"><div><b>Question 1</b><p>What is the main teaching problem?</p></div><div><b>Question 2</b><p>What classroom fact or limitation should you consider first?</p></div><div><b>Question 3</b><p>What information would you need before deciding?</p></div></div><div class="field"><label for="sc-context">Your short analysis</label><textarea id="sc-context" rows="5" placeholder="Write 2–4 sentences.">${esc(st.responses.context||'')}</textarea></div><button class="primary-btn" data-action="sixcNext">Continue to Consult →</button></div>`}
 else if(stage===1){html=`<div class="question-card"><div class="q-meta"><span class="pill">2. Consult</span></div><h2 class="q-title">Consult Gemini</h2><p>Get an AI response, then examine it. <b>Treat the response as a claim to examine, not as a final answer.</b></p>${st.ai?`<div class="feedback"><h3>🤖 Gemini response</h3><p class="ai-response">${esc(st.ai.response)}</p><h4>Claims to check</h4><ul>${(st.ai.claims_to_check||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Possible assumptions</h4><ul>${(st.ai.possible_assumptions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p><b>Uncertainty:</b> ${esc(st.ai.uncertainty||'Verify important claims.')}</p><p><b>Question:</b> ${esc(st.ai.follow_up_question||'What would you verify?')}</p></div><button class="primary-btn" data-action="sixcNext">Continue to Critique →</button>`:`<div class="feedback"><p>Gemini will give a useful but fallible response for you to analyze.</p><button class="primary-btn" data-action="consultAI">🤖 Get Gemini response</button></div>`}</div>`}
 else if(stage===2){html=`<div class="question-card"><div class="q-meta"><span class="pill">3. Critique</span></div><h2 class="q-title">Question the AI response</h2><div class="answer-summary"><div><b>What would you question?</b><p>Identify one part of the response that may be weak or incomplete.</p></div><div><b>What assumption?</b><p>Identify one assumption the AI appears to make.</p></div><div><b>What is missing?</b><p>State one piece of context or evidence that is missing.</p></div></div><div class="field"><label for="sc-critique">Your critique</label><textarea id="sc-critique" rows="6" placeholder="Explain your critique in simple English.">${esc(st.responses.critique||'')}</textarea></div><button class="primary-btn" data-action="sixcNext">Continue to Check →</button></div>`}
 else if(stage===3){const opts=s[3]||[];html=`<div class="question-card"><div class="q-meta"><span class="pill">4. Check</span></div><h2 class="q-title">Verify before accepting</h2><p>Choose what should be checked first, then explain how you would verify it.</p><div class="choices">${shuffle(opts).map((o,i)=>`<button class="choice ${st.responses.checkChoice===o?'selected':''}" data-check-choice="${esc(o)}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}</div><div class="field"><label for="sc-check">How would you verify the AI claim?</label><textarea id="sc-check" rows="5" placeholder="Name the source, evidence or comparison you would use.">${esc(st.responses.check||'')}</textarea></div><button class="primary-btn" data-action="sixcNext">Continue to Challenge →</button></div>`}
 else if(stage===4){html=`<div class="question-card"><div class="q-meta"><span class="pill">5. Challenge</span></div><h2 class="q-title">Improve or challenge the suggestion</h2><p>Do not simply accept or reject the AI. Propose a better option for this real classroom.</p><div class="answer-summary"><div><b>Alternative</b><p>What would you do differently?</p></div><div><b>Context</b><p>Why is your alternative more suitable?</p></div><div><b>Perspective</b><p>What other reasonable option exists?</p></div></div><div class="field"><label for="sc-challenge">Your alternative</label><textarea id="sc-challenge" rows="6" placeholder="Give your improved teaching option and reason.">${esc(st.responses.challenge||'')}</textarea></div><button class="primary-btn" data-action="sixcNext">Continue to Conclude →</button></div>`}
 else {html=`<div class="question-card"><div class="q-meta"><span class="pill">6. Conclude</span></div><h2 class="q-title">Make your final decision + reflect</h2><p>State your decision, reason, evidence/checking, and what you learned about using AI.</p><div class="field"><label for="sc-conclude">Final conclusion</label><textarea id="sc-conclude" rows="8" placeholder="My decision is... because... I checked... The AI response was useful for..., but... I learned that...">${esc(st.responses.conclude||'')}</textarea></div><button class="primary-btn" data-action="finishScenario">🎯 Complete 6C Activity</button></div>`}
 root.innerHTML=html;
}
function saveScenarioField(){const st=state.scenario;if(!st)return;const ids=['sc-context','sc-critique','sc-check','sc-challenge','sc-conclude'];const keys=['context','critique','check','challenge','conclude'];ids.forEach((id,i)=>{const el=document.getElementById(id);if(el)st.responses[keys[i]]=el.value.trim()})}
function sixcNext(){const st=state.scenario;if(!st)return;saveScenarioField();if(st.step===0&&!st.responses.context){toast('Write your short context analysis first.');return}if(st.step===2&&!st.responses.critique){toast('Write your critique first.');return}if(st.step===3&&(!st.responses.checkChoice||!st.responses.check)){toast('Choose a check and explain how you would verify it.');return}if(st.step===4&&!st.responses.challenge){toast('Write your alternative or improvement first.');return}if(st.step===1&&!st.ai){toast('Get the Gemini response before continuing.');return}st.step=Math.min(5,st.step+1);render();setTimeout(renderScenario,0);sound('click')}
async function consultAI(){const st=state.scenario;if(!st)return;saveScenarioField();const root=document.getElementById('sc-q');root.innerHTML='<div class="feedback"><b>🤖 Gemini is analyzing the classroom scenario…</b><p class="muted">Please wait.</p></div>';try{st.ai=await requestAI('Consult',st.responses.context,'Give a plausible but fallible response to the classroom situation. Include claims and assumptions the learner can examine.');award('ai');save();render();setTimeout(renderScenario,0);sound('correct')}catch(e){root.innerHTML='<div class="feedback"><b>AI service is temporarily unavailable.</b><p>You can continue the activity using your own reasoning and verification steps. The app has not treated an AI response as valid or correct.</p><button class="ghost-btn" data-action="retryConsult">Retry Gemini</button></div>';}}
async function retryConsult(){render();setTimeout(consultAI,0)}
function scoreText(t,terms=3){if(!t)return 0;const words=t.trim().split(/\s+/).filter(Boolean).length;let score=words>=45?3:words>=25?2:words>=10?1:0;const low=t.toLowerCase();const hits=['because','evidence','check','source','however','alternative','reason','context','verify','might','could'].filter(x=>low.includes(x)).length;score=Math.max(score,Math.min(3,Math.floor(hits/Math.max(1,terms))));return score}
function sixcRubric(st){const r={Context:scoreText(st.responses.context),Consult:st.ai?2:0,Critique:scoreText(st.responses.critique),Check:st.responses.checkChoice&&st.responses.check?scoreText(st.responses.check):0,Challenge:scoreText(st.responses.challenge),Conclude:scoreText(st.responses.conclude)};return r}
function finishScenario(){const st=state.scenario;if(!st)return;saveScenarioField();if(!st.responses.conclude){toast('Write your final conclusion and reflection first.');return}const rubric=sixcRubric(st),total=Object.values(rubric).reduce((a,b)=>a+b,0),max=18;st.completed=true;state.xp+=Math.round(total*5);state.answered+=6;state.correct+=total>=12?1:0;state.streak=total>=12?state.streak+1:0;state.best=Math.max(state.best,state.streak);award('thinker');state.history.unshift({date:new Date().toLocaleString(),type:'6C Activity',score:`${total}/${max}`,questions:6,scenario:st.s[0],rubric,conclusion:st.responses.conclude});state.history=state.history.slice(0,50);save();confetti();sound('win');const labels=['Context','Consult','Critique','Check','Challenge','Conclude'];document.getElementById('sc-q').innerHTML=`<div class="feedback pop"><strong>🎯 6C activity complete</strong><p>Your result is a learning activity score, not a validated psychological measurement.</p><div class="stats">${labels.map(x=>`<div class="stat"><strong>${rubric[x]}/3</strong><span>${x}</span></div>`).join('')}</div><div class="answer-summary"><div><b>Total</b><p>${total}/${max}</p></div><div><b>Final conclusion</b><p>${esc(st.responses.conclude)}</p></div></div><p><b>Strength:</b> ${total>=12?'You connected reasoning, verification and a final judgement.':'You completed the full cycle; strengthen the evidence and explanation in your next attempt.'}</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="primary-btn" data-action="newScenario">🔀 New 6C scenario</button><button class="ghost-btn" data-nav="progress">📈 My progress</button></div></div>`}
'''
s=s[:start]+new+s[end:]
# replace AI endpoint save default and aiCoach function behavior to use Gemini endpoint
ai_start=s.index('async function aiCoach(){')
ai_end=s.index('function aiExample(){', ai_start)
new_ai=r'''async function aiCoach(){
 const input=document.getElementById('ai-input')?.value.trim();if(!input){toast('Write your answer first.');return}
 const box=document.getElementById('ai-result');box.innerHTML='<span class="muted">🤖 Gemini is thinking…</span>';
 try{const r=await fetch(aiEndpoint(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'critical-thinking-feedback',stage:'AI Coach',scenario:'A future English teacher is evaluating an AI-supported classroom decision.',task:'Give one strength, one claim to verify, one possible alternative and one follow-up question. Do not give the final answer.',studentResponse:input})});if(!r.ok)throw new Error('AI');const d=await r.json();box.innerHTML=`<div class="ai-response"><b>${esc(d.response||'')}</b>\n\nClaims to check:\n${(d.claims_to_check||[]).map(x=>'• '+esc(x)).join('\n')}\n\nPossible assumptions:\n${(d.possible_assumptions||[]).map(x=>'• '+esc(x)).join('\n')}\n\nUncertainty: ${esc(d.uncertainty||'Verify important claims.')}\n\nFollow-up: ${esc(d.follow_up_question||'What could change your decision?')}</div>`;award('ai');state.xp+=20;save()}catch(e){box.innerHTML='<div class="feedback"><b>AI service is temporarily unavailable.</b><p>Check the backend connection. Your answer has not been presented as scientifically evaluated.</p></div>';}
}
'''
s=s[:ai_start]+new_ai+s[ai_end:]
# remove optional endpoint UI wording and input, make status informational
s=s.replace('<div class="card ai-connection">\n   <h3>AI connection</h3>\n   <p class="muted">The interface is ready for a secure Gemini/Claude/OpenAI backend. A private API key must not be placed in this GitHub Pages code.</p>\n   <div class="field"><label>Secure AI endpoint (optional)</label><input id="ai-endpoint" value="${esc(state.aiEndpoint)}" placeholder="https://your-server.example/api/ai"></div>\n   <button class="ghost-btn" data-action="saveAI">💾 Save connection</button>\n </div>', '<div class="card ai-connection"><h3>🔐 AI is managed by the platform</h3><p class="muted">Students do not need an API key. Gemini access is handled by the secure backend configured by the project administrator.</p></div>')
# event handlers
s=s.replace("else if(a==='finishScenario')finishScenario();", "else if(a==='finishScenario')finishScenario();\n else if(a==='sixcNext')sixcNext();\n else if(a==='consultAI')consultAI();\n else if(a==='retryConsult')retryConsult();")
s=s.replace("const sAns=e.target.closest('[data-scenario-answer]');if(sAns){document.querySelectorAll('[data-scenario-answer]').forEach(b=>b.classList.remove('selected'));sAns.classList.add('selected');sound('click');return}", "const sAns=e.target.closest('[data-scenario-answer]');if(sAns){document.querySelectorAll('[data-scenario-answer]').forEach(b=>b.classList.remove('selected'));sAns.classList.add('selected');sound('click');return}\n const cAns=e.target.closest('[data-check-choice]');if(cAns){state.scenario.responses.checkChoice=cAns.dataset.checkChoice;document.querySelectorAll('[data-check-choice]').forEach(b=>b.classList.remove('selected'));cAns.classList.add('selected');sound('click');return}")
# fix team badge timing
s=s.replace("award('team');renderCompetition();sound('start')", "renderCompetition();sound('start')")
s=s.replace("state.history.unshift({date:new Date().toLocaleString(),type:'Team Competition'", "award('team');state.history.unshift({date:new Date().toLocaleString(),type:'Team Competition'")
# update feature text Reflect->Conclude
s=s.replace('Context → Consult → Critique → Check → Challenge → Reflect','Context → Consult → Critique → Check → Challenge → Conclude')
s=s.replace('AI endpoint can be connected later via Settings -> AI endpoint.','Gemini AI is connected through a secure backend; students never enter an API key.')
p.write_text(s)
