/* AI-CT TEACHER — Sarvinoz Solexonovna | SamDChTI
   Standalone educational app. No external libraries required.
   AI endpoint can be connected later via Settings -> AI endpoint.
*/
(() => {
'use strict';

const AUTHOR='Sarvinoz Solexonovna';
const INSTITUTION='Samarkand State Institute of Foreign Languages (SamDChTI)';
const APP='AI-CT TEACHER';
const METHODS=[
 ['Evidence before conclusion','Use evidence before accepting a claim','🔎'],
 ['Socratic questioning','Ask questions that uncover assumptions','❓'],
 ['Compare perspectives','Examine more than one reasonable viewpoint','🪞'],
 ['Cause and effect','Separate causes, effects and coincidences','🔗'],
 ['Claim–Evidence–Reasoning','Connect a claim to evidence and reasoning','🧩'],
 ['Fact vs opinion','Distinguish verifiable facts from personal views','⚖️'],
 ['Source evaluation','Check who created information and why','🌐'],
 ['Bias detection','Look for wording, selection and framing bias','🧠'],
 ['Problem decomposition','Break a large problem into smaller parts','🧱'],
 ['Counterargument','Test an idea against a credible alternative','🥊'],
 ['Reflection','Review how and why you reached a conclusion','🪞'],
 ['Decision matrix','Compare choices using explicit criteria','📊']
];
const CATEGORIES=[
 ['Critical Thinking','🧠','Reasoning, evidence and judgement'],['AI & Teaching','🤖','AI in real English lessons'],['Fact Checking','🔍','Claims, sources and verification'],['Communication','💬','Clear questions, dialogue and feedback'],['Ethics','⚖️','Fair, responsible and human-centred AI'],['Media & Information','📰','Posts, headlines and digital information'],['Teaching Methods','👩‍🏫','Practical classroom decisions'],['Problem Solving','💡','Break down and solve teaching problems']
];
const STAGES=[['Context','Set the real situation','📍'],['Consult','Use AI as a source to examine','🤖'],['Critique','Question the response','🧐'],['Check','Verify evidence','🔍'],['Challenge','Test another possibility','⚔️'],['Conclude','Make a reasoned judgement','🎯'],['Reflect','Explain what you learned','🪞']];
const BADGES=[['first','First Step','Complete your first activity','🌱'],['sharp','Sharp Eye','Get 5 correct answers in a row','👁️'],['checker','Fact Checker','Complete a verification task','🔎'],['thinker','Deep Thinker','Finish a 7C task','🧠'],['team','Team Player','Finish a competition','🤝'],['streak','Hot Streak','Reach a 7-answer streak','🔥'],['ai','AI Critic','Use AI Coach feedback','🤖'],['master','Critical Thinker','Earn 1000 XP','🏆']];

function Q(id,method,diff,text,options,correct,why){return {id,method,diff,text,options,correct,why};}
const METHOD_BANK=[
Q('m01','Evidence before conclusion','Easy','A student says: “The new app improved my English because I used it for one week.” What should you ask first?',['What evidence shows improvement?','Who designed the app?','Was the app colourful?','Did the student like the logo?'],'What evidence shows improvement?','One week of use does not by itself prove improvement.'),
Q('m02','Evidence before conclusion','Medium','A teacher reports higher test scores after using AI. Which extra information is most useful?',['Scores from before the AI was used','The teacher’s favourite AI tool','The colour of the classroom','The number of slides in the lesson'],'Scores from before the AI was used','A before-and-after comparison gives a stronger basis for the claim.'),
Q('m03','Evidence before conclusion','Advanced','Two groups used different English courses and one scored higher. What is the key caution?',['Other differences may explain the result','The higher score is always caused by the course','Tests never provide evidence','The lower group did not study at all'],'Other differences may explain the result','A comparison needs attention to alternative explanations.'),
Q('m04','Evidence before conclusion','Easy','A classmate says an AI answer is correct because it sounds professional. What is missing?',['Evidence or a reliable source','A longer sentence','More emojis','A faster internet connection'],'Evidence or a reliable source','Professional wording is not proof.'),
Q('m05','Evidence before conclusion','Medium','Which statement is strongest for academic discussion?',['“The source reports X; we should verify it before accepting it.”','“It sounds true, so it is true.”','“Everyone online agrees.”','“AI said it, so it must be correct.”'],'“The source reports X; we should verify it before accepting it.”','It separates the reported claim from your judgement.'),
Q('m06','Socratic questioning','Easy','A student writes: “Online learning is better.” Which question best opens deeper thinking?',['Better in what way, and for whom?','How many words are in the sentence?','Can you type it again?','What colour is the website?'],'Better in what way, and for whom?','The question asks the learner to define criteria and scope.'),
Q('m07','Socratic questioning','Medium','A student says: “AI always saves teachers time.” Which question tests the assumption?',['When might AI require extra checking or editing?','What is the teacher’s age?','Does AI have a logo?','How long is the word “always”?'],'When might AI require extra checking or editing?','It directly tests the absolute assumption.'),
Q('m08','Socratic questioning','Advanced','Which question most effectively challenges a proposed classroom rule?',['What evidence suggests this rule works, and what exceptions exist?','Who first wrote the rule?','Is the rule written in English?','Can we make the rule shorter?'],'What evidence suggests this rule works, and what exceptions exist?','It requests evidence and considers exceptions.'),
Q('m09','Socratic questioning','Easy','A peer claims “students hate presentations.” What should you ask?',['How do we know, and which students?','Can we cancel presentations?','Did AI say it?','Are presentations old-fashioned?'],'How do we know, and which students?','It asks for evidence and avoids overgeneralisation.'),
Q('m10','Socratic questioning','Medium','Which follow-up best clarifies “AI is useful”?',['Useful for which task and under what conditions?','Is AI expensive?','Does AI have a human voice?','Is AI popular?'],'Useful for which task and under what conditions?','Good questioning turns a vague claim into a testable one.'),
Q('m11','Compare perspectives','Easy','A teacher wants to use AI feedback. Which perspective should be considered besides the teacher’s?',['Students’ learning needs and concerns','Only the software company','Only the fastest student','Nobody else'],'Students’ learning needs and concerns','A classroom decision affects learners as well as teachers.'),
Q('m12','Compare perspectives','Medium','A university is considering AI translation tools. Which pair gives a balanced discussion?',['Benefits for access and risks of inaccurate translation','Only cost and colour','Only student excitement','Only the developer’s opinion'],'Benefits for access and risks of inaccurate translation','A balanced view includes benefits and limitations.'),
Q('m13','Compare perspectives','Advanced','A student says AI feedback is objective. Which perspective challenges this most directly?',['The possibility that the model reflects data or design limitations','The keyboard layout','The student’s handwriting','The classroom temperature'],'The possibility that the model reflects data or design limitations','AI outputs can reflect limitations in data, design and context.'),
Q('m14','Compare perspectives','Easy','When choosing a group project topic, why ask all team members?',['Different experiences may reveal different useful concerns','It makes the project longer','It guarantees agreement','It removes the need for evidence'],'Different experiences may reveal different useful concerns','Perspective diversity can expose issues one person misses.'),
Q('m15','Compare perspectives','Medium','A new teaching method looks successful. What perspective might question the result?',['A teacher who used it with a different student group','Only the marketing team','Only the author of the method','Nobody'],'A teacher who used it with a different student group','Context can change how a method works.'),
Q('m16','Cause and effect','Easy','Attendance increased after a new timetable. What should you avoid saying immediately?',['The timetable definitely caused the increase','Attendance changed','The two events happened together','More information is needed'],'The timetable definitely caused the increase','Other factors may have changed at the same time.'),
Q('m17','Cause and effect','Medium','Students who practise more often score higher. What is a reasonable interpretation?',['Practice may contribute, but other factors should be considered','Practice always causes every score','Scores cause practice in every case','There is no relationship at all'],'Practice may contribute, but other factors should be considered','A relationship is not automatically a complete causal explanation.'),
Q('m18','Cause and effect','Advanced','A school buys tablets and reading scores rise. Which design would better test the causal claim?',['Compare similar groups over time with a clear plan','Ask whether teachers like tablets','Count the number of tablet cases','Use only one student’s opinion'],'Compare similar groups over time with a clear plan','A planned comparison helps separate the intervention from other changes.'),
Q('m19','Cause and effect','Easy','Which phrase signals caution about causation?',['“may have contributed to”','“definitely proves”','“always causes”','“everyone knows”'],'“may have contributed to”','The wording recognises uncertainty.'),
Q('m20','Cause and effect','Medium','A student blames low grades only on difficult vocabulary. What should they examine?',['Other possible causes such as practice, instructions and time','Only the vocabulary list','Nothing else','The teacher’s phone'],'Other possible causes such as practice, instructions and time','Good reasoning considers alternative explanations.'),
Q('m21','Claim–Evidence–Reasoning','Easy','Which sentence is evidence rather than a claim?',['In our class survey, 18 of 25 students preferred pair work.','Pair work is the best method.','Teachers should always use pairs.','Pair work is exciting.'],'In our class survey, 18 of 25 students preferred pair work.','The sentence reports collected data.'),
Q('m22','Claim–Evidence–Reasoning','Medium','A student claims AI feedback improves writing. Which evidence fits best?',['A comparison of writing quality before and after feedback','A screenshot of the AI logo','A friend saying AI is smart','The number of AI users'],'A comparison of writing quality before and after feedback','The evidence directly relates to writing improvement.'),
Q('m23','Claim–Evidence–Reasoning','Advanced','What is the role of reasoning in CER?',['Explain why the evidence supports the claim','Add more decoration','Repeat the claim','Replace evidence with opinion'],'Explain why the evidence supports the claim','Reasoning connects evidence to the conclusion.'),
Q('m24','Claim–Evidence–Reasoning','Easy','Which is the best claim?',['“In this class, pair work increased participation during today’s task.”','“Pair work is perfect.”','“Everyone loves pair work.”','“Pair work never fails.”'],'“In this class, pair work increased participation during today’s task.”','It is specific and appropriately limited.'),
Q('m25','Claim–Evidence–Reasoning','Medium','A student has strong evidence but no explanation. What is missing?',['A clear link between the evidence and the claim','More evidence from social media','A longer title','A new font'],'A clear link between the evidence and the claim','Evidence becomes persuasive when its relevance is explained.'),
Q('m26','Fact vs opinion','Easy','Which is most clearly a fact that can be checked?',['The university library opens at 8:00 on Monday.','The library is beautiful.','The library is the best place to study.','The library feels boring.'],'The university library opens at 8:00 on Monday.','A schedule can be verified.'),
Q('m27','Fact vs opinion','Medium','“AI is the most exciting invention of the decade.” This is mainly a…',['Opinion','Measured fact','Official statistic','Verified timetable'],'Opinion','“Most exciting” depends on judgement and criteria.'),
Q('m28','Fact vs opinion','Advanced','Which sentence carefully separates fact from interpretation?',['“The report lists a 12% increase; the author interprets this as improved engagement.”','“The report proves students love the course.”','“12% means the course is perfect.”','“The author must be right.”'],'“The report lists a 12% increase; the author interprets this as improved engagement.”','It distinguishes reported information from interpretation.'),
Q('m29','Fact vs opinion','Easy','“Our teacher is the kindest teacher in Samarkand” is difficult to verify mainly because…',['“kindest” needs a clear measurement or criterion','teachers cannot be compared','Samarkand has no teachers','the sentence is too short'],'“kindest” needs a clear measurement or criterion','The evaluative term needs an agreed criterion.'),
Q('m30','Fact vs opinion','Medium','Which question helps turn an opinion into a testable claim?',['What would count as evidence for this view?','Who likes this opinion?','Can we make it louder?','What emoji fits it?'],'What would count as evidence for this view?','A criterion for evidence makes the idea testable.'),
Q('m31','Source evaluation','Easy','Before trusting a website about education policy, what should you check?',['Who published it and when','Its background colour','Its number of emojis','Its font size'],'Who published it and when','Publisher and date help establish context and authority.'),
Q('m32','Source evaluation','Medium','A blog gives a statistic but no source. What is the best next step?',['Find the original data or a credible source','Share it immediately','Assume the number is true','Only check comments'],'Find the original data or a credible source','Traceable evidence is stronger than an unsupported statistic.'),
Q('m33','Source evaluation','Advanced','Two websites report different numbers. What should you compare first?',['Definitions, dates, methods and original sources','Which website looks nicer','Which number is larger','Which title is shorter'],'Definitions, dates, methods and original sources','Different measurement choices can explain different numbers.'),
Q('m34','Source evaluation','Easy','A source written by an unnamed person should be treated as…',['Information that needs extra verification','Automatically false','Automatically true','Official government evidence'],'Information that needs extra verification','Lack of authorship information reduces transparency.'),
Q('m35','Source evaluation','Medium','Why is publication date important?',['Information and policies can change over time','Old sources are always false','New sources are always true','Dates prove authors are experts'],'Information and policies can change over time','Currency matters when facts or rules change.'),
Q('m36','Bias detection','Easy','A headline says: “AI DESTROYS traditional teaching!” What should you notice?',['Loaded language may influence the reader','The headline is definitely false','The article is definitely true','The writer is a teacher'],'Loaded language may influence the reader','Strong wording can frame a story before evidence is examined.'),
Q('m37','Bias detection','Medium','A survey asks only students who already use AI whether AI is useful. What issue is possible?',['Selection bias','Perfect neutrality','Random sampling','Causal proof'],'Selection bias','The sample may not represent students who do not use AI.'),
Q('m38','Bias detection','Advanced','A university advertises a study funded by a company selling the tool. What should readers do?',['Consider the funding relationship and inspect the study methods','Reject the study automatically','Accept it automatically','Ignore the methods'],'Consider the funding relationship and inspect the study methods','Funding is relevant context, but method quality still matters.'),
Q('m39','Bias detection','Easy','Which phrase is more neutral?',['“The tool produced mixed results across groups.”','“The amazing tool transformed everyone.”','“The terrible tool failed completely.”','“Only careless teachers dislike it.”'],'“The tool produced mixed results across groups.”','It reports variation without loaded judgement.'),
Q('m40','Bias detection','Medium','If a post shows only positive student comments, what is missing?',['Possible negative or different experiences','More emojis','A longer caption','A larger image'],'Possible negative or different experiences','Selective examples can create a one-sided picture.'),
Q('m41','Problem decomposition','Easy','A lesson is failing. What is a useful first move?',['Break the problem into specific parts','Change everything at once','Blame the students','Stop the course'],'Break the problem into specific parts','Smaller components are easier to diagnose.'),
Q('m42','Problem decomposition','Medium','Students struggle with presentations. Which breakdown is useful?',['Ideas, language, organisation, confidence and delivery','Only grammar','Only classroom size','Only the projector'],'Ideas, language, organisation, confidence and delivery','The problem may have several distinct causes.'),
Q('m43','Problem decomposition','Advanced','A teacher wants to “improve critical thinking.” What should be clarified first?',['Which observable skills and tasks will show improvement','Which app icon to use','How many posters to print','Which music to play'],'Which observable skills and tasks will show improvement','A broad goal needs measurable learning behaviours.'),
Q('m44','Problem decomposition','Easy','Which plan is easiest to evaluate?',['Improve source checking by practising three verification steps','Make students smarter','Make lessons better','Use more technology'],'Improve source checking by practising three verification steps','It identifies a concrete skill and action.'),
Q('m45','Problem decomposition','Medium','A group project is late. Which first diagnosis is most useful?',['Check task division, deadlines, communication and workload','Punish the whole group','Delete the project','Assume laziness'],'Check task division, deadlines, communication and workload','Diagnosis should identify the actual bottleneck.'),
Q('m46','Counterargument','Easy','A counterargument is…',['A reasonable alternative that challenges part of your claim','An insult','A repeated conclusion','A random fact'],'A reasonable alternative that challenges part of your claim','It pressure-tests the original position.'),
Q('m47','Counterargument','Medium','A student says “AI should never be used in education.” What is a useful counterargument?',['Some controlled uses may support learning when students verify outputs','AI is always perfect','Teachers are unnecessary','Students should never use computers'],'Some controlled uses may support learning when students verify outputs','A counterargument can challenge an absolute claim without accepting the opposite extreme.'),
Q('m48','Counterargument','Advanced','Which response shows mature reasoning?',['“This evidence supports my view, but a different context could produce another result.”','“My evidence ends the discussion.”','“Anyone who disagrees is wrong.”','“I do not need evidence.”'],'“This evidence supports my view, but a different context could produce another result.”','It recognises limits and alternative conditions.'),
Q('m49','Counterargument','Easy','Why use a counterexample?',['To test whether a claim is too broad','To make a paragraph longer','To avoid evidence','To confuse the reader'],'To test whether a claim is too broad','One credible exception can reveal overgeneralisation.'),
Q('m50','Counterargument','Medium','A student claims “group work always increases participation.” What could challenge it?',['A group with unequal participation despite using group work','A colourful group poster','A longer group name','A positive emoji'],'A group with unequal participation despite using group work','A concrete exception tests the word “always.”'),
Q('m51','Reflection','Easy','After an AI task, which reflection question is most useful?',['What did I accept, question and verify?','Did I finish quickly?','Was the screen bright?','Did the AI use emojis?'],'What did I accept, question and verify?','It focuses reflection on critical-thinking behaviour.'),
Q('m52','Reflection','Medium','A student changed their answer after checking a source. What does this show?',['Willingness to revise a conclusion using evidence','Weakness','Failure to think','No learning'],'Willingness to revise a conclusion using evidence','Changing a conclusion when evidence changes is a strength of reasoning.'),
Q('m53','Reflection','Advanced','Which reflection best supports metacognition?',['“My first assumption was X; after checking Y, I changed my reasoning because…”','“I got the answer.”','“AI was helpful.”','“The task was easy.”'],'“My first assumption was X; after checking Y, I changed my reasoning because…”','It makes the reasoning process visible.'),
Q('m54','Reflection','Easy','What should a student record after a fact-checking task?',['What source changed or confirmed their judgement','Only the final score','Only the time used','Only the title'],'What source changed or confirmed their judgement','The learning value is in the reasoning and evidence trail.'),
Q('m55','Reflection','Medium','Why is reflection placed after conclusion in the 7C cycle?',['It helps learners examine how they reached the conclusion','Because reflection is unrelated to reasoning','To replace evidence','To avoid discussion'],'It helps learners examine how they reached the conclusion','Reflection turns the activity into learning about thinking.'),
Q('m56','Decision matrix','Easy','When choosing between two lesson tools, a decision matrix helps you…',['Compare both using the same criteria','Choose the newest tool automatically','Avoid criteria','Use only personal preference'],'Compare both using the same criteria','Explicit criteria make the decision more transparent.'),
Q('m57','Decision matrix','Medium','Which criterion is especially important when selecting an AI classroom tool?',['Privacy and student data handling','Logo colour','Number of emojis','Animation speed'],'Privacy and student data handling','Responsible educational technology requires attention to data.'),
Q('m58','Decision matrix','Advanced','A teacher values cost, learning value, accessibility and privacy. What should happen before scoring tools?',['Define what each criterion means','Pick the winner first','Ignore accessibility','Let the most expensive tool win'],'Define what each criterion means','Clear definitions make comparisons more consistent.'),
Q('m59','Decision matrix','Easy','If two tools have the same score, what can you do?',['Review the most important criteria and gather more evidence','Pretend one won','Choose randomly without explanation','Delete both'],'Review the most important criteria and gather more evidence','A tie is a signal to inspect decision priorities.'),
Q('m60','Decision matrix','Medium','Why should criteria be visible to students?',['They can understand and challenge the basis of the decision','It makes the lesson longer','It prevents discussion','It guarantees agreement'],'They can understand and challenge the basis of the decision','Transparent criteria support reasoned discussion.')
];

const COMP_EXTRA=[
['A Telegram group shares: “This AI detector is 100% accurate.” What should a student do first?',['Ask for evidence of accuracy and the test conditions','Forward it to everyone','Trust the percentage','Use it without checking'],'Ask for evidence of accuracy and the test conditions'],
['A teacher receives an AI-generated lesson plan with a UK classroom example. What is the most useful check for Uzbekistan?',['Adapt examples, curriculum and classroom realities before use','Copy it exactly','Delete every activity','Assume all education systems work the same'],'Adapt examples, curriculum and classroom realities before use'],
['A student uses AI to write an essay and submits it unchanged. Which issue should the class discuss?',['Learning ownership, transparency and responsible use','Only font size','Only internet speed','Whether AI has a logo'],'Learning ownership, transparency and responsible use'],
['A viral post says “Students learn twice as fast with AI.” What is missing?',['A clear study, sample, measure and source','More hashtags','A longer headline','A bigger image'],'A clear study, sample, measure and source'],
['Two students disagree about a translation. What is the best next step?',['Compare context, dictionaries and original meaning','Vote immediately','Ask which student is louder','Choose the longer translation'],'Compare context, dictionaries and original meaning'],
['A teacher wants AI feedback for every student. What is a sensible human-centred approach?',['Use AI as support and keep teacher judgement and student dialogue','Let AI grade everything automatically','Remove teacher feedback','Hide AI use from students'],'Use AI as support and keep teacher judgement and student dialogue'],
['A student finds an official-looking PDF with no date. What should they do?',['Look for a current version and verify the issuing organisation','Assume it is current','Use it as the newest source','Ignore all official documents'],'Look for a current version and verify the issuing organisation'],
['A group project has one student doing all the work. Which response is most useful?',['Review roles, workload and deadlines with the group','Give everyone the same mark immediately','Cancel the project','Blame the quiet students'],'Review roles, workload and deadlines with the group'],
['An AI answer gives a confident but unfamiliar historical claim. What is the best response?',['Pause and verify it with a reliable source','Repeat it confidently','Add more details from AI','Treat confidence as evidence'],'Pause and verify it with a reliable source'],
['A teacher wants to use an AI image in a presentation. What should be considered?',['Accuracy, relevance, permissions and misleading representation','Only image size','Only how funny it looks','Nothing'],'Accuracy, relevance, permissions and misleading representation'],
['A student says “Everyone in my group agrees.” What should a critical thinker ask?',['How did you check everyone’s view?','Why are you speaking English?','Can we finish now?','What colour is the poster?'],'How did you check everyone’s view?'],
['A university changes an online learning platform. What should teachers check before the first lesson?',['Access, student devices, support and task compatibility','Only the logo','Only the launch date','Only the platform slogan'],'Access, student devices, support and task compatibility'],
['A student sees two contradictory AI answers. What is a productive next step?',['Identify the exact claim and check external evidence','Choose the first answer','Choose the longer answer','Ask AI which answer is prettier'],'Identify the exact claim and check external evidence'],
['A class survey has only 8 volunteers. What should the report say?',['The results describe those respondents and may not represent the whole class','The results represent everyone','The results prove a national trend','The survey is useless'],'The results describe those respondents and may not represent the whole class'],
['A teacher wants to reduce cheating with AI. Which approach is more educational?',['Design tasks requiring explanation, sources, drafts and reflection','Only threaten students','Ban every digital tool','Ignore the issue'],'Design tasks requiring explanation, sources, drafts and reflection'],
['A student says “The source is famous, so it must be right.” What is the missing step?',['Check the specific claim, evidence and date','Memorise the source name','Count its followers','Copy its wording'],'Check the specific claim, evidence and date'],
['An AI tool suggests an activity that requires expensive equipment. What should a teacher do?',['Adapt it to realistic local resources','Use it unchanged','Cancel English lessons','Assume every student has the equipment'],'Adapt it to realistic local resources'],
['A teacher notices quiet students rarely speak in group work. Which question is useful?',['What group structure or turn-taking rule could increase participation?','Why are they always quiet?','Can we remove them?','Can AI speak for them?'],'What group structure or turn-taking rule could increase participation?'],
['A student finds a statistic in a social-media graphic. What should they locate?',['The original source and definition of the statistic','The graphic designer','More reposts','The number of likes'],'The original source and definition of the statistic'],
['A teacher gets an AI answer with no sources. What is a safe academic move?',['Treat it as a draft and verify important claims','Publish it immediately','Assume citations are hidden','Use it as official policy'],'Treat it as a draft and verify important claims'],
['A student says “This method works because it is popular.” What reasoning problem appears?',['Popularity is not the same as evidence of effectiveness','Popularity proves causation','Popularity is irrelevant to all questions','Popularity is a source'],'Popularity is not the same as evidence of effectiveness'],
['A group must choose between two lesson plans. What is a transparent approach?',['Set criteria, compare evidence and explain the choice','Let the fastest speaker decide','Pick the prettier plan','Avoid discussion'],'Set criteria, compare evidence and explain the choice'],
['A teacher receives negative student feedback. What is a critical response?',['Look for patterns and specific evidence before changing the course','Ignore all feedback','Change everything immediately','Blame students'],'Look for patterns and specific evidence before changing the course'],
['An AI response gives an example from another country. What should a future teacher ask?',['Does the example fit our students, curriculum and context?','Is the country famous?','Is the example longer?','Does AI prefer that country?'],'Does the example fit our students, curriculum and context?']
].map((x,i)=>Q('c'+String(i+1).padStart(2,'0'),'Competition',i%3===0?'Easy':i%3===1?'Medium':'Advanced',x[0],x[1],x[2],'A strong answer explains the reasoning and checks context rather than relying on confidence or popularity.'));

const SCENARIOS=[
['AI homework','Your English methodology lecturer asks students to use an AI tool to suggest three activities for teaching speaking. One suggestion looks useful, but another does not fit your class.','Which part of the AI response should you examine first?','How can you adapt the useful idea instead of copying it?'],
['Telegram claim','A Telegram channel says: “Students who use AI get higher grades.” No study is linked.','What evidence would you need before accepting the claim?','Which source would you search for first?'],
['Presentation feedback','A student asks AI to improve a presentation. AI changes the examples to situations from another country.','What should the student check?','How could the examples be made relevant to Uzbekistan?'],
['Online lesson','A teacher prepares an online English lesson. AI suggests an activity requiring every student to have a laptop, but some students only have phones.','What problem do you see?','How would you redesign the activity?'],
['Group work','Four students work on a project. One student writes almost everything while the others are silent.','What evidence would help explain the problem?','What group rule could make participation fairer?'],
['Fact-checking','An AI tool confidently says a new education rule started this semester.','What should you verify?','Why is confidence not enough?'],
['Essay writing','A student asks AI to write an entire essay and plans to submit it unchanged.','What learning is missing?','What responsible use of AI could still support the student?'],
['Translation','AI translates a classroom instruction, but the Uzbek version sounds unnatural and changes the meaning slightly.','What should be compared?','How would you verify the best wording?'],
['AI detector','A website claims its AI detector is 100% accurate.','What question should you ask about the claim?','What evidence would make the claim more credible?'],
['Social media','A popular post says a teaching method “works for every student.”','What word in the claim should make you cautious?','What kind of evidence would challenge the claim?'],
['Teacher feedback','A teacher uses AI to draft feedback. Some comments sound generic and do not match the student’s work.','What should the teacher do?','Why should human judgement remain important?'],
['Library source','Two websites give different statistics about university students.','What should you compare between the sources?','How would you decide which number is more trustworthy?'],
['Exam preparation','AI creates 20 exam questions. Five are unrelated to the course outcomes.','What should the teacher check?','How can AI be used without replacing teacher planning?'],
['Privacy','A free AI website asks students to upload their full personal profiles before giving feedback.','What concern appears?','What safer alternative could a teacher use?'],
['Attendance','Attendance increases after a timetable change. The teacher says the timetable caused it.','What alternative explanations could exist?','What evidence would strengthen the causal claim?'],
['Debate','A student says: “Everyone in our class agrees that AI is good.”','What should you ask before accepting this statement?','How could you collect a fairer range of views?'],
['Course choice','Students must choose between two English learning platforms. One is cheaper; the other has better accessibility features.','What criteria should be compared?','Why should criteria be agreed before choosing?'],
['News headline','A news post says: “AI DESTROYS traditional education!”','How does the wording affect the reader?','How would you rewrite the claim more neutrally?'],
['AI lesson plan','AI suggests a speaking activity with 45 students standing in a circle. The real class has fixed desks and limited space.','What part of the suggestion needs checking?','How can the activity be adapted?'],
['Research result','A small class survey finds 7 of 10 students prefer AI feedback.','What can the result reasonably tell you?','What should you avoid claiming?'],
['Source conflict','An official page from last year and a recent university notice give different information.','Which details should you compare?','Why does date matter?'],
['Plagiarism concern','A student paraphrases AI output but cannot explain the ideas in their own words.','What does this reveal about learning?','What task could require genuine understanding?'],
['Peer disagreement','Two students give different answers to a critical-thinking question. Both have some evidence.','What should they compare?','How can they reach a reasoned conclusion?'],
['Future teacher','You are preparing your first English lesson using AI.','What should you decide before opening the AI tool?','How can the 7C cycle keep you in control of the lesson?']
];

const state={page:'home',name:localStorage.getItem('aict_name')||'Student',xp:+localStorage.getItem('aict_xp')||0,correct:+localStorage.getItem('aict_correct')||0,answered:+localStorage.getItem('aict_answered')||0,streak:+localStorage.getItem('aict_streak')||0,best:+localStorage.getItem('aict_best')||0,badges:JSON.parse(localStorage.getItem('aict_badges')||'[]'),history:JSON.parse(localStorage.getItem('aict_history')||'[]'),sound:localStorage.getItem('aict_sound')!=='off',aiEndpoint:localStorage.getItem('aict_ai_endpoint')||'',libraryFilter:'All',libraryCategory:null,game:null,competition:null,ai:null};
function save(){for(const [k,v] of Object.entries({aict_name:state.name,aict_xp:state.xp,aict_correct:state.correct,aict_answered:state.answered,aict_streak:state.streak,aict_best:state.best,aict_badges:JSON.stringify(state.badges),aict_history:JSON.stringify(state.history),aict_sound:state.sound?'on':'off',aict_ai_endpoint:state.aiEndpoint}))localStorage.setItem(k,v)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function shuffle(a){const x=a.slice();for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function sample(a,n){return shuffle(a).slice(0,n)}
function level(){return Math.floor(state.xp/250)+1}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
function sound(type){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);const map={click:[300,.06],correct:[660,.13],wrong:[170,.18],start:[420,.1],win:[[523,659,784],.14],tick:[420,.05],badge:[880,.12]};let m=map[type]||map.click;const tones=Array.isArray(m[0])?m[0]:[m[0]];let t=c.currentTime;tones.forEach((f,i)=>{const x=c.createOscillator(),gg=c.createGain();x.frequency.value=f;x.type='sine';x.connect(gg);gg.connect(c.destination);gg.gain.setValueAtTime(.0001,t+i*.1);gg.gain.exponentialRampToValueAtTime(.08,t+i*.1+.015);gg.gain.exponentialRampToValueAtTime(.0001,t+i*.1+.09);x.start(t+i*.1);x.stop(t+i*.1+.1)});o.stop();g.gain.value=.0001}catch(e){}}
function confetti(){const c=document.createElement('div');c.className='confetti';for(let i=0;i<70;i++){const p=document.createElement('i');p.style.left=Math.random()*100+'%';p.style.setProperty('--x',(Math.random()*300-150)+'px');p.style.background=['#7c5cff','#19d3ae','#ffc857','#ff6685','#fff'][i%5];p.style.animationDelay=Math.random()*.4+'s';c.appendChild(p)}document.body.appendChild(c);setTimeout(()=>c.remove(),2300)}
function award(id){if(state.badges.includes(id))return;state.badges.push(id);const b=BADGES.find(x=>x[0]===id);if(b){sound('badge');toast(`${b[3]} Badge unlocked: ${b[1]}`)}}
function earn(xp,good=true){state.xp+=xp;state.answered++;if(good){state.correct++;state.streak++;state.best=Math.max(state.best,state.streak);if(state.streak>=5)award('sharp');if(state.streak>=7)award('streak')}else state.streak=0;if(state.answered===1)award('first');if(state.xp>=1000)award('master');save()}
function nav(page){state.page=page;state.libraryCategory=null;render();window.scrollTo({top:0,behavior:'smooth'});sound('click')}
function shell(content){return `<div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark">🧠</div><div><strong>${APP}</strong><small>${INSTITUTION}</small></div></div><div class="top-actions"><span class="pill">Lv ${level()} · ${state.xp} XP</span><button class="icon-btn" data-action="sound" title="Sound">${state.sound?'🔊':'🔇'}</button><button class="icon-btn" data-action="profile">👤</button></div></header><div class="layout"><aside class="sidebar">${navHTML()}<div class="side-card"><small>${esc(state.name)}</small><div class="xpbar"><i style="width:${Math.min(100,state.xp%250/2.5)}%"></i></div><small>${state.xp%250}/250 XP to next level</small></div></aside><main class="main">${content}<div class="footer">${APP} · ${AUTHOR} · ${INSTITUTION}<br><small>AI is a thinking partner, not a substitute for evidence, teacher judgement or student reflection.</small></div></main></div>${mobileNav()}</div>`}
function navHTML(){const items=[['home','🏠','Home'],['library','📚','Task Library'],['cycle','🧠','7C Cycle'],['challenge','🎮','Method Challenge'],['competition','🏆','Team Competition'],['ai','🤖','AI Critical Thinking Lab'],['progress','📈','My Progress'],['teacher','👩‍🏫','Teacher Dashboard']];return `<nav class="nav-group">${items.map(i=>`<button class="nav-item ${state.page===i[0]?'active':''}" data-nav="${i[0]}"><span class="nav-icon">${i[1]}</span>${i[2]}</button>`).join('')}</nav>`}
function mobileNav(){return `<div class="mobile-nav">${[['home','🏠'],['library','📚'],['challenge','🎮'],['competition','🏆'],['progress','📈']].map(x=>`<button class="${state.page===x[0]?'active':''}" data-nav="${x[0]}">${x[1]}<br>${x[0]}</button>`).join('')}</div>`}
function home(){const features=[['library','📚','Task Library','Short real-life scenarios across 8 critical-thinking areas.'],['cycle','🧠','7C Cycle','Context → Consult → Critique → Check → Challenge → Conclude → Reflect.'],['challenge','🎮','Method Challenge','Fast, varied multiple-choice practice with 60+ questions.'],['competition','🏆','Team Competition','Solo or team quiz with timer, score and random questions.'],['ai','🤖','AI Critical Thinking Lab','AI-ready coaching, prompt practice and reasoning feedback.'],['progress','📈','My Progress','XP, streaks, badges and learning history.'],['teacher','👩‍🏫','Teacher Dashboard','Classroom-ready activity overview and quick launch tools.'],['library','🇺🇿','Uzbekistan Context','Situations built around university, English teaching and local realities.']];return shell(`<section class="hero"><span class="eyebrow">Artificial Intelligence · Critical Thinking · English Teacher Education</span><h1>Think first. Check twice. Teach better.</h1><p>A modern learning environment for future English teachers. Use AI as something to question, verify, challenge and reflect on — not simply as an answer machine.</p><div class="author"><div class="avatar">SS</div><div><strong>${AUTHOR}</strong><br><span class="muted">${INSTITUTION} · PhD Research Project</span></div></div><div style="margin-top:20px;display:flex;gap:10px;flex-wrap:wrap"><button class="primary-btn" data-nav="cycle">🚀 Start 7C Learning</button><button class="ghost-btn" data-nav="challenge">🎮 Quick Challenge</button></div></section><div class="stats"><div class="stat"><strong>${state.xp}</strong><span>Total XP</span></div><div class="stat"><strong>${state.correct}</strong><span>Correct answers</span></div><div class="stat"><strong>${state.best}</strong><span>Best streak</span></div><div class="stat"><strong>${state.badges.length}</strong><span>Badges</span></div></div><div class="section-title"><div><h2>Learning Studio</h2><p>Choose a route — every route strengthens critical thinking.</p></div></div><div class="grid grid-4">${features.map(f=>`<button class="card feature-card" data-nav="${f[0]}"><div class="big-icon">${f[1]}</div><h3>${f[2]}</h3><p>${f[3]}</p><span class="arrow">→</span></button>`).join('')}</div><div class="section-title"><div><h2>AI-CT 7C Cycle</h2><p>Seven small moves that keep the learner in control.</p></div></div><div class="cycle">${STAGES.map((s,i)=>`<div class="cycle-step"><b>${s[2]}</b><strong>${i+1}. ${s[0]}</strong><span>${s[1]}</span></div>`).join('')}</div>`)}
function library(){let tasks=[];if(state.libraryCategory){tasks=SCENARIOS.map((s,i)=>({i,title:s[0],scenario:s[1],cat:CATEGORIES[i%8][0]})).filter(x=>x.cat===state.libraryCategory)}else tasks=SCENARIOS.map((s,i)=>({i,title:s[0],scenario:s[1],cat:CATEGORIES[i%8][0]}));return shell(`<div class="section-title"><div><h2>📚 Task Library</h2><p>Short, practical scenarios. No heavy vocabulary. No unnecessary reading.</p></div><span class="pill">${SCENARIOS.length} scenarios</span></div><div class="tabs"><button class="chip ${!state.libraryCategory?'active':''}" data-cat="All">All</button>${CATEGORIES.map(c=>`<button class="chip ${state.libraryCategory===c[0]?'active':''}" data-cat="${esc(c[0])}">${c[1]} ${c[0]}</button>`).join('')}</div><div class="grid grid-4">${tasks.map(t=>`<article class="card task-card"><div class="task-icon">${CATEGORIES[t.i%8][1]}</div><span class="pill">${t.cat}</span><h3>${esc(t.title)}</h3><p class="muted">${esc(t.scenario)}</p><div class="task-foot"><small class="muted">2 critical questions</small><button class="primary-btn" data-scenario="${t.i}">Open →</button></div></article>`).join('')}</div>`)}
function cycle(){return shell(`<div class="game-shell"><div class="section-title"><div><h2>🧠 AI-CT 7C Cycle</h2><p>One short scenario. Two strong questions. Seven thinking moves.</p></div><span class="pill">Student-friendly</span></div><div class="cycle">${STAGES.map((s,i)=>`<div class="cycle-step"><b>${s[2]}</b><strong>${i+1}. ${s[0]}</strong><span>${s[1]}</span></div>`).join('')}</div><div class="card" style="margin-top:16px"><div class="scenario"><span class="pill">Real-life scenario</span><h2 id="sc-title">Ready when you are.</h2><p id="sc-text">Choose “Start scenario” and a random Uzbekistan-friendly teaching situation will appear. You will answer only two questions.</p></div><div id="sc-q" style="margin-top:14px"></div><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:16px"><button class="primary-btn" data-action="startScenario">🚀 Start scenario</button><button class="ghost-btn" data-action="newScenario">🔀 New scenario</button></div></div></div>`)}
function startScenario(){const i=Math.floor(Math.random()*SCENARIOS.length);const s=SCENARIOS[i];state.scenario={i,s,answers:[],step:0};renderScenario();sound('start')}
function renderScenario(){const root=document.getElementById('sc-q'),s=state.scenario;if(!root||!s)return;const q=s.step===0?s.s[2]:s.s[3];root.innerHTML=`<div class="question-card pop"><div class="q-meta"><span class="pill">7C · ${s.step+1}/2</span><span class="muted">${s.s[0]}</span></div><h2 class="q-title">${esc(q)}</h2><textarea id="sc-answer" rows="5" placeholder="Write your reasoning in 2–5 sentences..."></textarea><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="primary-btn" data-action="submitScenario">${s.step===0?'Continue →':'Finish 7C ✓'}</button></div></div>`}
function submitScenario(){const a=document.getElementById('sc-answer')?.value.trim();if(!a){toast('Write a short reasoning first.');return}state.scenario.answers.push(a);if(state.scenario.step===0){state.scenario.step=1;renderScenario();return}state.xp+=80;state.answered+=2;state.correct+=2;state.streak+=2;state.best=Math.max(state.best,state.streak);award('thinker');save();const s=state.scenario.s;document.getElementById('sc-q').innerHTML=`<div class="feedback pop"><strong>🎯 7C reflection complete</strong><p>You considered the situation and explained your reasoning. Now ask yourself: what evidence would change your conclusion?</p><div class="grid grid-2"><div><small class="muted">Your first reasoning</small><p>${esc(state.scenario.answers[0])}</p></div><div><small class="muted">Your second reasoning</small><p>${esc(state.scenario.answers[1])}</p></div></div><button class="primary-btn" data-action="newScenario">🔀 Try another random scenario</button></div>`;confetti();sound('win')}
function gameSetup(kind){const title=kind==='challenge'?'🎮 Method Challenge':'🏆 Team Competition';return shell(`<div class="game-shell"><div class="section-title"><div><h2>${title}</h2><p>${kind==='challenge'?'60+ questions across 12 reasoning methods.':'60+ core questions + local teaching scenarios. Randomised every round.'}</p></div></div><div class="card"><div class="grid grid-2"><div class="field"><label>Difficulty</label><select id="g-diff"><option>Mixed</option><option>Easy</option><option>Medium</option><option>Advanced</option></select></div><div class="field"><label>Questions</label><select id="g-count"><option value="10">10</option><option value="15">15</option><option value="20">20</option><option value="30">30</option><option value="40">40</option><option value="50">50</option><option value="60">60</option><option value="80">80</option></select></div></div>${kind==='competition'?`<div class="field"><label>Teams</label><select id="team-count"><option value="1">Solo</option><option value="2">2 teams</option><option value="3">3 teams</option><option value="4">4 teams</option></select></div><div id="team-fields" class="team-grid"></div>`:''}<button class="primary-btn" data-action="beginGame" data-kind="${kind}">🚀 Start ${kind==='challenge'?'Challenge':'Competition'}</button></div></div>`)}
function buildQuestions(kind,diff,count){let bank=kind==='challenge'?METHOD_BANK:METHOD_BANK.concat(COMP_EXTRA);if(diff!=='Mixed')bank=bank.filter(q=>q.diff===diff);bank=shuffle(bank);let selected=[];const seen=new Set();for(const q of bank){if(!seen.has(q.id)){selected.push(q);seen.add(q.id)}if(selected.length>=Math.min(count,bank.length))break}return selected}
function beginGame(kind){const diff=document.getElementById('g-diff')?.value||'Mixed';const count=+document.getElementById('g-count')?.value||10;let qs=buildQuestions(kind,diff,count);if(kind==='challenge'){state.game={kind,qs,index:0,score:0,answered:false};award('first');renderGame();sound('start')}else{const n=+(document.getElementById('team-count')?.value||1);const names=[];for(let i=0;i<n;i++)names.push(document.getElementById('team-'+i)?.value||`Team ${i+1}`);state.competition={kind,qs,index:0,team:0,teams:names.map((name)=>({name,score:0,correct:0})),answered:false,timer:null,seconds:20};award('team');renderCompetition();sound('start')}}
function renderGame(){const g=state.game;if(!g)return;const q=g.qs[g.index];const opts=shuffle(q.options.map((text)=>({text,correct:text===q.correct})));g.currentOpts=opts;const content=`<div class="game-shell"><div class="game-head"><button class="ghost-btn" data-nav="challenge">← Exit</button><div class="progress-track"><i style="width:${(g.index/g.qs.length)*100}%"></i></div><span class="pill">${g.index+1}/${g.qs.length}</span><span class="pill">${g.score} XP</span></div><div class="question-card"><div class="q-meta"><span class="pill">${q.method}</span><span class="pill">${q.diff}</span></div><h1 class="q-title">${esc(q.text)}</h1><div class="choices">${opts.map((o,i)=>`<button class="choice" data-answer="${i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></button>`).join('')}</div><div id="game-feedback"></div></div></div>`;document.getElementById('app').innerHTML=shell(content);}
function answerGame(i){const g=state.game;if(!g||g.answered)return;g.answered=true;const q=g.qs[g.index],o=g.currentOpts[i],buttons=[...document.querySelectorAll('[data-answer]')];buttons.forEach((b,idx)=>{if(g.currentOpts[idx].correct)b.classList.add('correct');if(idx===i&&!o.correct)b.classList.add('wrong')});const good=o.correct;if(good){sound('correct');earn(25);g.score+=25;g.score+=Math.max(0,5-(g.index%5));}else{sound('wrong');earn(5,false)}if(good&&state.streak>=5)toast('🔥 Great streak!');document.getElementById('game-feedback').innerHTML=`<div class="feedback ${good?'pop':'shake'}"><strong>${good?'✅ Correct!':'❌ Not quite.'}</strong><p>${esc(q.why)}</p><button class="primary-btn" data-action="nextGame">${g.index===g.qs.length-1?'Finish':'Next random question →'}</button></div>`;save()}
function nextGame(){const g=state.game;if(!g)return;if(g.index>=g.qs.length-1){award('sharp');confetti();sound('win');state.history.unshift({date:new Date().toLocaleString(),type:'Method Challenge',score:g.score,questions:g.qs.length});state.history=state.history.slice(0,20);save();state.game=null;toast('Challenge complete!');nav('progress');return}g.index++;g.answered=false;renderGame()}
function renderCompetition(){const c=state.competition;if(!c)return;const q=c.qs[c.index],opts=shuffle(q.options.map(text=>({text,correct:text===q.correct})));c.currentOpts=opts;const scores=c.teams.map((t,i)=>`<div class="score ${i===c.team?'leader':''}"><span>${i===c.team?'🎯 ':''}${esc(t.name)}</span><strong>${t.score}</strong><small>${t.correct} correct</small></div>`).join('');document.getElementById('app').innerHTML=shell(`<div class="game-shell"><div class="game-head"><button class="ghost-btn" data-nav="competition">← Exit</button><span class="pill">${c.index+1}/${c.qs.length}</span><span class="pill">${esc(c.teams[c.team].name)} turn</span><span id="comp-timer" class="timer">20</span></div><div class="scoreboard">${scores}</div><div class="question-card" style="margin-top:15px"><div class="q-meta"><span class="pill">${q.diff}</span><span class="pill">${q.method}</span></div><h1 class="q-title">${esc(q.text)}</h1><div class="choices">${opts.map((o,i)=>`<button class="choice" data-comp-answer="${i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></button>`).join('')}</div><div id="comp-feedback"></div></div></div>`);startCompTimer()}
function startCompTimer(){const c=state.competition;if(!c)return;clearInterval(c.timer);c.seconds=20;const el=document.getElementById('comp-timer');c.timer=setInterval(()=>{c.seconds--;if(el){el.textContent=c.seconds;el.classList.toggle('hot',c.seconds<=5)}sound(c.seconds<=5?'tick':'click');if(c.seconds<=0){clearInterval(c.timer);answerCompetition(-1)}},1000)}
function answerCompetition(i){const c=state.competition;if(!c||c.answered)return;c.answered=true;clearInterval(c.timer);const q=c.qs[c.index],o=i>=0?c.currentOpts[i]:null,good=!!o?.correct;c.teams[c.team].score+=good?100:0;c.teams[c.team].correct+=good?1:0;earn(good?15:2,good);const buttons=[...document.querySelectorAll('[data-comp-answer]')];buttons.forEach((b,idx)=>{if(c.currentOpts[idx].correct)b.classList.add('correct');if(idx===i&&!good)b.classList.add('wrong')});if(good)sound('correct');else sound('wrong');document.getElementById('comp-feedback').innerHTML=`<div class="feedback"><strong>${good?'🎯 Correct!':'⏱ Time/answer used.'}</strong><p>${esc(q.why)}</p><button class="primary-btn" data-action="nextCompetition">${c.index===c.qs.length-1?'Final scoreboard':'Next team →'}</button></div>`;save()}
function nextCompetition(){const c=state.competition;if(!c)return;if(c.index>=c.qs.length-1){clearInterval(c.timer);confetti();sound('win');state.history.unshift({date:new Date().toLocaleString(),type:'Team Competition',score:c.teams.reduce((a,t)=>a+t.score,0),questions:c.qs.length,teams:c.teams.map(t=>`${t.name}: ${t.score}`).join(' · ')});state.history=state.history.slice(0,20);save();const winner=c.teams.slice().sort((a,b)=>b.score-a.score)[0];const body=`<div class="game-shell"><div class="hero"><span class="eyebrow">Competition complete</span><h1>🏆 ${esc(winner.name)}</h1><p>Final scoreboard. The result shows the game score; it is not a research measure of critical thinking ability.</p></div><div class="scoreboard" style="margin-top:18px">${c.teams.map(t=>`<div class="score ${t===winner?'leader':''}"><span>${esc(t.name)}</span><strong>${t.score}</strong><small>${t.correct} correct</small></div>`).join('')}</div><div style="margin-top:18px;display:flex;gap:10px"><button class="primary-btn" data-nav="competition">🔁 Play again</button><button class="ghost-btn" data-nav="progress">📈 My Progress</button></div></div>`;state.competition=null;document.getElementById('app').innerHTML=shell(body);return}c.index++;c.team=(c.team+1)%c.teams.length;c.answered=false;renderCompetition()}
function competitionSetup(){return gameSetup('competition')}
function progress(){return shell(`<div class="section-title"><div><h2>📈 My Progress</h2><p>Personal activity indicators — not a validated psychological measurement.</p></div><button class="ghost-btn" data-action="profile">Edit profile</button></div><div class="stats"><div class="stat"><strong>${state.xp}</strong><span>XP</span></div><div class="stat"><strong>${state.correct}</strong><span>Correct</span></div><div class="stat"><strong>${state.best}</strong><span>Best streak</span></div><div class="stat"><strong>${level()}</strong><span>Level</span></div></div><div class="section-title"><div><h2>Badges</h2></div></div><div class="badge-grid">${BADGES.map(b=>`<span class="badge ${state.badges.includes(b[0])?'':'muted'}">${b[3]} ${b[1]} ${state.badges.includes(b[0])?'✓':'○'}</span>`).join('')}</div><div class="section-title"><div><h2>Recent activity</h2></div></div><div class="card">${state.history.length?`<table class="table"><thead><tr><th>Date</th><th>Activity</th><th>Score</th><th>Questions</th></tr></thead><tbody>${state.history.map(h=>`<tr><td>${esc(h.date)}</td><td>${esc(h.type)}</td><td>${esc(h.score)}</td><td>${esc(h.questions)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No activity yet. Start a challenge to build your learning history.</div>'}</div>`)}
function teacher(){const total=METHOD_BANK.length+COMP_EXTRA.length;return shell(`<div class="section-title"><div><h2>👩‍🏫 Teacher Dashboard</h2><p>Quick classroom tools and transparent activity information.</p></div><span class="pill">Local demo dashboard</span></div><div class="grid grid-3"><div class="card"><h3>Question bank</h3><strong style="font-size:34px">${total}+</strong><p class="muted">Randomised core questions across methods and teaching scenarios.</p></div><div class="card"><h3>7C scenarios</h3><strong style="font-size:34px">${SCENARIOS.length}</strong><p class="muted">Short Uzbekistan-friendly scenarios, two questions each.</p></div><div class="card"><h3>Student activity</h3><strong style="font-size:34px">${state.answered}</strong><p class="muted">Answers recorded on this device.</p></div></div><div class="section-title"><div><h2>Launch in class</h2><p>Use a projector or students’ phones.</p></div></div><div class="grid grid-3"><button class="card feature-card" data-nav="challenge"><div class="big-icon">🎮</div><h3>Method Challenge</h3><p>Fast individual practice.</p></button><button class="card feature-card" data-nav="competition"><div class="big-icon">🏆</div><h3>Team Competition</h3><p>Turn-taking and scoreboard.</p></button><button class="card feature-card" data-nav="cycle"><div class="big-icon">🧠</div><h3>7C Scenario</h3><p>Short reasoning activity.</p></button></div><div class="card" style="margin-top:16px"><h3>Teacher note</h3><p class="muted">The current dashboard is device-local. It does not claim to show a shared class database. A future backend can add secure student accounts, class codes, aggregate analytics and exportable research data.</p></div>`)}
function aiLab(){return shell(`<div class="section-title"><div><h2>🤖 AI Critical Thinking Lab</h2><p>AI is treated as a source to question, verify and improve — not as an authority.</p></div><span class="pill">AI-ready</span></div><div class="ai-box"><div class="grid grid-2"><div><h3>AI Coach</h3><p class="muted">Paste a student answer or AI response. The local coach will identify reasoning strengths, missing evidence and a next question. If a secure AI endpoint is configured, the same interface can send the task to it.</p><textarea id="ai-input" rows="9" placeholder="Example: AI says group work always improves speaking... What do you think?"></textarea><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:10px"><button class="primary-btn" data-action="aiCoach">🧠 Analyse reasoning</button><button class="ghost-btn" data-action="aiPrompt">✨ Give me a prompt</button></div></div><div><h3>AI-CT prompt pattern</h3><div class="card"><p><b>Context:</b> Give the real classroom situation.</p><p><b>Question:</b> Ask AI for a suggestion, not a final decision.</p><p><b>Challenge:</b> Ask what could be wrong.</p><p><b>Check:</b> Request sources or verification steps.</p><p><b>Reflect:</b> Explain what you accepted, changed or rejected.</p></div><div id="ai-result" class="feedback"><span class="muted">Your analysis will appear here.</span></div></div></div></div><div class="section-title"><div><h2>Connection</h2><p>For production AI, use a secure backend/serverless endpoint. Never place a private API key in this GitHub Pages frontend.</p></div></div><div class="card"><div class="field"><label>Secure AI endpoint (optional)</label><input id="ai-endpoint" value="${esc(state.aiEndpoint)}" placeholder="https://your-secure-endpoint.example/api/ai"></div><button class="primary-btn" data-action="saveAI">💾 Save connection</button><p class="muted" style="font-size:13px">Expected POST body: { action, prompt, context }. Expected response: { text } or plain text.</p></div>`)}
async function aiCoach(){const input=document.getElementById('ai-input')?.value.trim();if(!input){toast('Paste an answer or AI response first.');return}award('ai');const box=document.getElementById('ai-result');box.innerHTML='<span class="muted">Thinking…</span>';if(state.aiEndpoint){try{const r=await fetch(state.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'critical-thinking-feedback',prompt:input,context:{cycle:'AI-CT 7C',institution:INSTITUTION}})});if(!r.ok)throw new Error('Endpoint error');const data=await r.json().catch(()=>null);const text=data?.text||data?.response||'The AI endpoint returned no text.';box.innerHTML=`<div class="ai-response">${esc(text)}</div>`;return}catch(e){toast('AI endpoint could not be reached; using local coach.')}}const lower=input.toLowerCase();const flags=[];if(/always|never|everyone|nobody|100%|definitely/.test(lower))flags.push('absolute wording — test whether exceptions exist');if(!/source|evidence|study|data|research|report/.test(lower))flags.push('no clear evidence or source is mentioned');if(!/because|therefore|reason|since|so that/.test(lower))flags.push('reasoning link is not explicit');if(!/however|although|alternative|other|different|but/.test(lower))flags.push('no alternative explanation or counterargument');const feedback=`Strength to keep: you have made a claim that can be examined.\n\nCritical-thinking check:\n${flags.length?flags.map(x=>'• '+x).join('\n'):'• Your answer already includes some reasoning language — now make the evidence trail explicit.'}\n\nNext question:\nWhat evidence would make you change or strengthen your conclusion?\n\n7C reminder:\nContext → Consult → Critique → Check → Challenge → Conclude → Reflect`;box.innerHTML=`<div class="ai-response">${esc(feedback)}</div>`;state.xp+=20;save()}
function aiPrompt(){const p=sample(['Act as a critical-thinking coach. Do not give me the final answer. Give me two possible explanations, one assumption I should question, and three verification steps. Context: an English lesson in a university in Uzbekistan.','I am a future English teacher. Give me a short classroom scenario where an AI answer might look correct but contain a hidden problem. Then ask me two questions that make me check it.','Review this teaching idea using the 7C cycle. Focus on context, evidence, alternative explanations and reflection. Do not make the decision for me.'],1)[0];document.getElementById('ai-input').value=p;toast('A new critical-thinking prompt is ready.')}
function profile(){const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-box"><div class="modal-head"><h2>👤 Student profile</h2><button class="icon-btn" data-close>✕</button></div><div class="field"><label>Name</label><input id="profile-name" value="${esc(state.name)}"></div><div style="display:flex;gap:10px;justify-content:flex-end"><button class="ghost-btn" data-close>Cancel</button><button class="primary-btn" data-save-profile>Save</button></div></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target.hasAttribute('data-close'))modal.remove();if(e.target.hasAttribute('data-save-profile')){state.name=document.getElementById('profile-name').value.trim()||'Student';save();modal.remove();render()}})}
function render(){let c='';switch(state.page){case'home':c=home();break;case'library':c=library();break;case'cycle':c=cycle();break;case'challenge':c=gameSetup('challenge');break;case'competition':c=competitionSetup();break;case'ai':c=aiLab();break;case'progress':c=progress();break;case'teacher':c=teacher();break;default:c=home()}document.getElementById('app').innerHTML=c}

document.addEventListener('click',e=>{const navEl=e.target.closest('[data-nav]');if(navEl){nav(navEl.dataset.nav);return}const cat=e.target.closest('[data-cat]');if(cat){state.libraryCategory=cat.dataset.cat==='All'?null:cat.dataset.cat;render();return}const scenario=e.target.closest('[data-scenario]');if(scenario){nav('cycle');setTimeout(()=>{startSpecific(+scenario.dataset.scenario)},0);return}const ans=e.target.closest('[data-answer]');if(ans){answerGame(+ans.dataset.answer);return}const cans=e.target.closest('[data-comp-answer]');if(cans){answerCompetition(+cans.dataset.compAnswer);return}const act=e.target.closest('[data-action]');if(!act)return;const a=act.dataset.action;if(a==='sound'){state.sound=!state.sound;save();render();sound('click')}else if(a==='profile')profile();else if(a==='startScenario')startScenario();else if(a==='newScenario')startScenario();else if(a==='submitScenario')submitScenario();else if(a==='beginGame')beginGame(act.dataset.kind);else if(a==='nextGame')nextGame();else if(a==='nextCompetition')nextCompetition();else if(a==='aiCoach')aiCoach();else if(a==='aiPrompt')aiPrompt();else if(a==='saveAI'){state.aiEndpoint=document.getElementById('ai-endpoint').value.trim();save();toast('AI connection setting saved.');}});
document.addEventListener('input',e=>{if(e.target.id==='team-count'){const n=+e.target.value;const box=document.getElementById('team-fields');if(box)box.innerHTML=n>1?Array.from({length:n},(_,i)=>`<div class="team-box"><div class="field"><label>Team ${i+1} name</label><input id="team-${i}" value="Team ${i+1}"></div></div>`).join(''):''}});
function startSpecific(i){state.scenario={i,s:SCENARIOS[i%SCENARIOS.length],answers:[],step:0};document.getElementById('sc-title').textContent=state.scenario.s[0];document.getElementById('sc-text').textContent=state.scenario.s[1];renderScenario();sound('start')}
render();
})();
